/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiE2eAutomatedRequestRouteImport } from './routes/api/e2e/automated-request'
import { Route as ApiV1ContentRequestsRouteImport } from './routes/api/v1/content-requests'
import { Route as AppRequestsRequestIdRouteImport } from './routes/app.requests.$requestId'
import { Route as ApiV1CliContentRequestsRouteImport } from './routes/api/v1/cli/content-requests'
import { Route as ApiV1ContentRequestsRequestIdRouteImport } from './routes/api/v1/content-requests.$requestId'
import { Route as ApiV1CliContentRequestsRequestIdRouteImport } from './routes/api/v1/cli/content-requests.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eAutomatedRequestRoute = ApiE2eAutomatedRequestRouteImport.update({
  id: '/api/e2e/automated-request',
  path: '/api/e2e/automated-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContentRequestsRoute = ApiV1ContentRequestsRouteImport.update({
  id: '/api/v1/content-requests',
  path: '/api/v1/content-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1CliContentRequestsRoute = ApiV1CliContentRequestsRouteImport.update({
  id: '/api/v1/cli/content-requests',
  path: '/api/v1/cli/content-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContentRequestsRequestIdRoute =
  ApiV1ContentRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => ApiV1ContentRequestsRoute,
  } as any)
const ApiV1CliContentRequestsRequestIdRoute =
  ApiV1CliContentRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => ApiV1CliContentRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/new': typeof AppNewRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/e2e/automated-request': typeof ApiE2eAutomatedRequestRoute
  '/api/v1/content-requests': typeof ApiV1ContentRequestsRouteWithChildren
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/api/v1/cli/content-requests': typeof ApiV1CliContentRequestsRouteWithChildren
  '/api/v1/content-requests/$requestId': typeof ApiV1ContentRequestsRequestIdRoute
  '/api/v1/cli/content-requests/$requestId': typeof ApiV1CliContentRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/new': typeof AppNewRoute
  '/app': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/e2e/automated-request': typeof ApiE2eAutomatedRequestRoute
  '/api/v1/content-requests': typeof ApiV1ContentRequestsRouteWithChildren
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/api/v1/cli/content-requests': typeof ApiV1CliContentRequestsRouteWithChildren
  '/api/v1/content-requests/$requestId': typeof ApiV1ContentRequestsRequestIdRoute
  '/api/v1/cli/content-requests/$requestId': typeof ApiV1CliContentRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/new': typeof AppNewRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/e2e/automated-request': typeof ApiE2eAutomatedRequestRoute
  '/api/v1/content-requests': typeof ApiV1ContentRequestsRouteWithChildren
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/api/v1/cli/content-requests': typeof ApiV1CliContentRequestsRouteWithChildren
  '/api/v1/content-requests/$requestId': typeof ApiV1ContentRequestsRequestIdRoute
  '/api/v1/cli/content-requests/$requestId': typeof ApiV1CliContentRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/unauthorized'
    | '/app/new'
    | '/app/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/e2e/automated-request'
    | '/api/v1/content-requests'
    | '/app/requests/$requestId'
    | '/api/v1/cli/content-requests'
    | '/api/v1/content-requests/$requestId'
    | '/api/v1/cli/content-requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/unauthorized'
    | '/app/new'
    | '/app'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/e2e/automated-request'
    | '/api/v1/content-requests'
    | '/app/requests/$requestId'
    | '/api/v1/cli/content-requests'
    | '/api/v1/content-requests/$requestId'
    | '/api/v1/cli/content-requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/unauthorized'
    | '/app/new'
    | '/app/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/e2e/automated-request'
    | '/api/v1/content-requests'
    | '/app/requests/$requestId'
    | '/api/v1/cli/content-requests'
    | '/api/v1/content-requests/$requestId'
    | '/api/v1/cli/content-requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiE2eAutomatedRequestRoute: typeof ApiE2eAutomatedRequestRoute
  ApiV1ContentRequestsRoute: typeof ApiV1ContentRequestsRouteWithChildren
  ApiV1CliContentRequestsRoute: typeof ApiV1CliContentRequestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/automated-request': {
      id: '/api/e2e/automated-request'
      path: '/api/e2e/automated-request'
      fullPath: '/api/e2e/automated-request'
      preLoaderRoute: typeof ApiE2eAutomatedRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/content-requests': {
      id: '/api/v1/content-requests'
      path: '/api/v1/content-requests'
      fullPath: '/api/v1/content-requests'
      preLoaderRoute: typeof ApiV1ContentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/requests/$requestId': {
      id: '/app/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/app/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/cli/content-requests': {
      id: '/api/v1/cli/content-requests'
      path: '/api/v1/cli/content-requests'
      fullPath: '/api/v1/cli/content-requests'
      preLoaderRoute: typeof ApiV1CliContentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/content-requests/$requestId': {
      id: '/api/v1/content-requests/$requestId'
      path: '/$requestId'
      fullPath: '/api/v1/content-requests/$requestId'
      preLoaderRoute: typeof ApiV1ContentRequestsRequestIdRouteImport
      parentRoute: typeof ApiV1ContentRequestsRoute
    }
    '/api/v1/cli/content-requests/$requestId': {
      id: '/api/v1/cli/content-requests/$requestId'
      path: '/$requestId'
      fullPath: '/api/v1/cli/content-requests/$requestId'
      preLoaderRoute: typeof ApiV1CliContentRequestsRequestIdRouteImport
      parentRoute: typeof ApiV1CliContentRequestsRoute
    }
  }
}

interface AppRouteChildren {
  AppNewRoute: typeof AppNewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNewRoute: AppNewRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1ContentRequestsRouteChildren {
  ApiV1ContentRequestsRequestIdRoute: typeof ApiV1ContentRequestsRequestIdRoute
}

const ApiV1ContentRequestsRouteChildren: ApiV1ContentRequestsRouteChildren = {
  ApiV1ContentRequestsRequestIdRoute: ApiV1ContentRequestsRequestIdRoute,
}

const ApiV1ContentRequestsRouteWithChildren =
  ApiV1ContentRequestsRoute._addFileChildren(ApiV1ContentRequestsRouteChildren)

interface ApiV1CliContentRequestsRouteChildren {
  ApiV1CliContentRequestsRequestIdRoute: typeof ApiV1CliContentRequestsRequestIdRoute
}

const ApiV1CliContentRequestsRouteChildren: ApiV1CliContentRequestsRouteChildren =
  {
    ApiV1CliContentRequestsRequestIdRoute:
      ApiV1CliContentRequestsRequestIdRoute,
  }

const ApiV1CliContentRequestsRouteWithChildren =
  ApiV1CliContentRequestsRoute._addFileChildren(
    ApiV1CliContentRequestsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiE2eAutomatedRequestRoute: ApiE2eAutomatedRequestRoute,
  ApiV1ContentRequestsRoute: ApiV1ContentRequestsRouteWithChildren,
  ApiV1CliContentRequestsRoute: ApiV1CliContentRequestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
